<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
  <meta charset="utf-8">
  <meta name="description" content="Nim fundamentals: Error handling. A tutorial for absolute beginners.">
  <meta name="author" content="Elucian Moise">
  <meta name="keywords" content="nim, lang, language, syntax, tutorial">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Website title -->
  <title>Nim Errors</title>

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
  <!-- Icon -->
  <link rel="icon" type="image/png"  href="https://sagecode.net/images/favicon.ico">
  <!-- Prism Highlighter -->
  <link rel="stylesheet" href="../prism.css">
  <script src="../prism.js"></script>
  <!-- custom css -->
  <link rel="stylesheet" href="https://sagecode.net/sage.css">
  </head>
<body>

<main class="container">

<header class="row">
    <div class="col">
        <a href="https://sagecode.net"><img src="https://sagecode.net/images/sage-logo.svg" alt="Sage-Code Laboratory" height="80"></a>
    </div>
    <div class="col  bottom-right">
        <a href="index.html#lang-index" rel="nofollow">index</a>&lt;--
    </div>
</header><hr>


<h2>Nim Errors</h2>


<div class="alert alert-secondary shadow-sm">
Errors can occur in Nim for a variety of reasons, such as invalid syntax, runtime errors, and errors in library code. When an error occurs, the Nim compiler will generate a stack trace that shows the location of the error in the code.
</div>

<p>In Nim exceptions are objects. By convention, exception types are suffixed with 'Error'. The system module defines an exception hierarchy that you might want to stick to. Exceptions derive from system.Exception, which provides the common interface.</p>

<div class="alert alert-warning"><b>Caution: </b>A convention is that exceptions should be raised in exceptional cases, they should not be used as an alternative method of control flow. Exceptions are more expensive and you should not do large programs in exception handlers.</div>


<h1>Error Handling in Nim</h1>

<p>Nim has three types of errors:</p>

<ul>
<li>Fatal errors</li>
<li>Errors</li>
<li>Warnings</li>
</ul>


<h2>Fatal Error</h2>

<p>The "try" keyword is used to execute a block of code that may contain errors. The "except" keyword is used to handle errors that occur in the "try" block.</p>

<pre><code class="language-nim">
try:
    x = 1 / 0
except FatalError:
    print("Fatal error")
</code></pre>

<p>In this example, the "try" block attempts to divide 1 by 0. This will cause a fatal error, which is handled by the "except" block. The "except" block prints the message "Fatal error".</p>

<h4>Errors</h4>

<p>Errors can be handled by returning an error value from a function. For example, the following code shows how to handle an error by returning an error value:</p>

<pre><code class="language-nim">
func divide(x: int, y: int) -> int:
if y == 0:
    return Error
return x / y
</code></pre>

<h2>Raise statement</h2>

<p>Raising an exception is done with the raise statement. Before you can raise an exception you can define an initialize an error.</p>

<pre><code class="language-nim line-numbers">
var
  e: ref OSError
new(e)
e.msg = "the request to the OS failed"
raise e
</code></pre>

<p>If the raise keyword is not followed by an expression, the last exception is re-raised. For the purpose of avoiding repeating this common code pattern, the template newException in the system module can be used:</p>

<pre><code class="language-nim">raise newException(OSError, "the request to the OS failed")</code></pre>

<h2>Error handling</h2>

<p>The "try" keyword is used to execute a block of code that may contain errors. The "except" keyword is used to handle errors that occur in the "try" block. The try statement handles exceptions:</p>


<div align="center">
  <img src="./img/nim-except.svg" alt="try except"
       width="460" class="img-fluid protect rounded shadow border" >
  <p>Try Statement</p>
</div>

<h2>Example</h2>

<pre><code class="language-nim line-numbers">
from std/strutils import parseInt

# read the first two lines of a text file that should contain numbers
# and tries to add them
var
  f: File
if open(f, "numbers.txt"):
  try:
    let a = readLine(f)
    let b = readLine(f)
    echo "sum: ", parseInt(a) + parseInt(b)
  except OverflowDefect:
    echo "overflow!"
  except ValueError:
    echo "could not convert string to integer"
  except IOError:
    echo "IO error!"
  except CatchableError:
    echo "Unknown exception!"
    # reraise the unknown exception:
    raise
  finally:
    close(f)
</code></pre>

<h4>Notes:</h4>

<p>1.The statements after the try are executed unless an exception is raised. Then the appropriate except part is executed.</p>

<p>2.The empty except part is executed if there is an exception that is not explicitly listed. It is similar to an else part in if statements.</p>

<p>3.If there is a finally part, it is always executed after the exception handlers.</p>

<p>The exception is consumed in an except part. If an exception is not handled, it is propagated through the call stack. This means that often the rest of the procedure - that is not within a finally clause - is not executed (if an exception occurs).
</p>

<p>If you need to access the actual exception object or message inside an except branch you can use the getCurrentException() and getCurrentExceptionMsg() procs from the system module.</p> 

<h4>Example:</h4>

<pre><code class="language-nim line-numbers">
try:
  doSomethingHere()
except CatchableError:
  let
    e = getCurrentException()
    msg = getCurrentExceptionMsg()
  echo "Got exception ", repr(e), " with message ", msg
</code></pre>

<!-- work in progress-->

<hr>
<p><b>Try this:</b>
<a href="index.html#quiz">Quiz</a>

<!-- Footer -->
<footer class="footer">
  <div class="footer-copyright text-center"></div>
</footer>
</main>
</body>
</html>