<!DOCTYPE html>
<html lang="en" data-bs-theme="dark"><head>
  <meta charset="utf-8">
  <meta name="author" content="Elucian Moise">
  <meta name="description" content="Handling exceptions in C++ language.">
  <meta name="keywords" content="cpp, exception, try, catch, throw, syntax">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Website title -->
  <title>C++ Exceptions</title>  

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
  <!-- Icon -->
  <link rel="icon" type="image/png"  href="https://sagecode.net/images/favicon.ico">  
  <!-- Prism Highlighter -->
  <link rel="stylesheet" href="../prism.css">
  <script src="../prism.js"></script>
  <!-- custom css -->
  <link rel="stylesheet" href="https://sagecode.net/sage.css">
</head>
<body>

<div class="container">
        
<!-- header -->
<header class="row">
    <div class="col">
        <a href="https://sagecode.net"><img src="https://sagecode.net/images/sage-logo.svg" alt="Sage-Code Laboratory" height="80"/></a>
    </div>  
    <div class="col  bottom-right">
        <a href="index.html#lang-index" rel="nofollow">index</a>&lt;--
    </div>
</header><hr>

<h1>C++ Exceptions</h1>

<div class="alert alert-secondary shadow-sm">
There is a new capability of C++ that is not available in C, called <em>exception.</em>
It represents an unusual situation that apears during program execution.
There are two kind of exceptions: system predefined and user defined.
We deal with exceptions to improve code reliability.
</div>

<h2>Exception Handling</h2>

<p>When an exception is encontered, the program will intrerupt its notmal workflow and jump to a different place. 
There is a new <em>"control flow"</em> statement created for handling exceptions. Let's study the workflow:</em>

<div align="center">
  <img src="img/cpp-try.svg" alt="try-catch diagram" width="540" 
       class="img-fluid protect rounded shadow border" >    
  <p>try-catch workflow</p>
</div> 

<hr>

<h4>Syntax:</h4>

<pre><code class="language-cpp">try {
   // protected code
} catch( ExceptionName e1 ) {
   // catch block
} catch( ExceptionName e2 ) {
   // catch block
} catch( ExceptionName eN ) {
   // catch block
} catch(...) {
   // catch any other exception
}
</code></pre>

<div class="alert alert-warning"><span style="color:brown">Missing Feature:</span> 
If you are Java programmer you may know there is a <em>"finally"</em> block in <em>"try"</em> statement.
Oh well, this is not implemented by C++ standard. 
This is maybe an inconvenient for developers who try to create safer code. 
We can argue why this feature is missing using Twitter.
</div>


<blockquote class="twitter-tweet" align="center"><p lang="en" dir="ltr">Wait a second. C++ do not have &quot;finally&quot; block in &quot;try-catch&quot; statement? This is ridiculous. But why?<a href="https://twitter.com/cppchat?ref_src=twsrc%5Etfw">@cppchat</a> <a href="https://twitter.com/include_cpp?ref_src=twsrc%5Etfw">@include_cpp</a> <a href="https://twitter.com/hashtag/cpp?src=hash&amp;ref_src=twsrc%5Etfw">#cpp</a></p>&mdash; Elucian Moise (@elucian_moise) <a href="https://twitter.com/elucian_moise/status/1329354172702093312?ref_src=twsrc%5Etfw">November 19, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<!-- work in progress-->

<hr>
<p><b>Go back to:</b>
<a href="index.html">C++ Tutorial</a></p>

<!-- Footer -->
<footer class="footer">
  <div class="footer-copyright text-center"></div>
</footer>
</div>
</body>
</html>