<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
  <meta charset="utf-8">
  <meta name="description" content="Introductory to error handling in Go. Computer programming tutorial.">
  <meta name="author" content="Elucian Moise">
  <meta name="keywords" content="go, golang, language, syntax, programming, tutorial, error, errors">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Website title -->
  <title>Go Errors</title>  

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
  <!-- Icon -->
  <link rel="icon" type="image/png"  href="https://sagecode.net/images/favicon.ico">  
  <!-- Prism Highlighter -->
  <link rel="stylesheet" href="https://sagecode.net/prism.css">
  <script src="https://sagecode.net/prism.js"></script>
  <!-- custom css -->
  <link rel="stylesheet" href="https://sagecode.net/sage.css">
  </head>
<body>

<div class="container">
        
<!-- header -->
<header class="row">
    <div class="col">
        <a href="https://sagecode.net"><img src="https://sagecode.net/images/sage-logo.svg" alt="Sage-Code Laboratory" height="80"></a>
    </div>  
    <div class="col  bottom-right">
        <a href="index.html#lang-index" rel="nofollow">index</a>&lt;--
    </div>
</header><hr>


<h2>Go Errors</h2>


<div class="alert alert-secondary shadow-sm">
One Go program can execute normally or can have errors. Go programs create error state with "error" values. Functions often return a value of type "error". Calling code that may fail should handle errors by testing whether the "error" is <em>nil</em>.
</div>

<p>
The <em>error</em> type is a built-in interface similar to fmt.Stringer. You can implement any struct that implements this interface and you have a kind of error.</p>

<pre><code class="language-go line-numbers">type error interface {
    Error() string
}</code></pre>

<p>As with <em>fmt.stringer</em> the <em>fmt</em> package looks for the <em>error</em> interface when printing values. In next fragment we demonstrate an error.</p>

<pre><code class="language-go line-numbers">i, err := strconv.Atoi("42")
if err != nil {
    fmt.Printf("couldn't convert number: %v\n", err)
    return
}
fmt.Println("Converted integer:", i)</code></pre>

<h4>Example:</h4>

<p>A nil error denotes success; a non-nil  error denotes failure. In next example we define a user error and we customize the error function:</p>

<pre><code class="language-go line-numbers">//file error_hnd.go
package main

import (
    "fmt"
    "time"
)

type MyError struct {
    When time.Time
    What string
}

func (e *MyError) Error() string {
    return fmt.Sprintf("at %v, %s",
        e.When, e.What)
}

func run() error {
    return &amp;MyError{
        time.Now(),
        "it didn't work",
    }
}

func main() {
    if err := run(); err != nil {
        fmt.Println(err)
    }
}</code></pre>

<h2>Panic statement</h2>

<p>We use "panic" keyword to intrerupt the program. Typically it means something went unexpectedly wrong. Mostly we use it to fail fast on errors that shouldn't occur during normal operation.</p>

<pre><code class="language-go line-numbers">
package main

import "os"

func main() {
    // how to panic
    panic("a problem")

    // handle error using panic
    _, err := os.Create("/tmp/file")
    if err != nil {
        panic(err)
    }
}
</code></pre>

<h2>Recovering</h2>

<p>Function recover() is provided for error handling. It must be called within a <em>a defer function</em>. When the enclosing function panics, the defer will activate and a recover() call within it will catch the panic error message and report it.</p>

<pre><code class="language-go line-numbers">
package funcs

import "fmt"

func TestRecover() {
    fmt.Println("protect this function")

    // create an anonymous function
    defer func() {
        if e := recover(); e != nil {
            // The return value of recover() is the error
            fmt.Println("Recovered from: ", e)
        }
    }()

    fmt.Println("get ready for panic")

    // create an error on purpose
    fmt.Println("paniking ...")
    panic("My error")

    // Next print will not run
    fmt.Println("This is not executed.")
}
</code></pre>

<h2>Exit status</h2>

<p>Go exit with return 0 from main() function. You can use os.Exit() in main() or in any other function to exit from application with a different status.</p>

<pre><code class="language-go line-numbers">
package demo

import (
   "fmt"
   "os"
)

func DemoExit() {
   // expect ths to print
   fmt.Println("exiting ...")

   // is this going to be print?
   defer fmt.Println("done !")

   os.Exit(3) // error
}
</code></pre>    

<h4>Output:</h4>

<pre class="output">
exiting ...
make: *** [Makefile:3: run] Error 3
exit status 2
</pre>

<!-- work in progress-->

<hr>
<p><b>Read next:</b>
<a href="files.html">Files & Folders</a></p>

<!-- Footer -->
<footer class="footer">
  <div class="footer-copyright text-center"></div>
</footer>
</div>
</body>
</html>